# Generated by Django 4.2.16 on 2024-09-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.company', verbose_name='Seller of the product'),
            preserve_default=False,
        ),
    ]
