# Generated by Django 4.2.16 on 2024-09-14 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ShoppingCart',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='ShoppingCartItem',
        ),
    ]
