# Generated by Django 4.2.16 on 2024-11-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='seller',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
