# Generated by Django 4.2.16 on 2024-09-23 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_companyproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproduct',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
