# Generated by Django 4.2.16 on 2024-11-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.item', verbose_name='items in shopping cart'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
