# Generated by Django 4.2.16 on 2024-11-27 01:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_item_amount_delete_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('user', 'product')},
        ),
    ]
