# Generated by Django 4.2.16 on 2024-11-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
