# Generated by Django 5.1.4 on 2024-12-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_review_unique_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
